EfCrud/Models/ErrorViewModel.cs
namespace EfCrud.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EfCrud/Controllers/HayvanlarController.cs
using EfCrud.Data;
using Microsoft.AspNetCore.Mvc;

namespace EfCrud.Controllers
{
    public class HayvanlarController : Controller
    {
        private readonly HayvanContext db;

        public HayvanlarController(HayvanContext context)
        {
            db = context;
        }
        public IActionResult Index()
        {
            return View(db.Hayvanlar.ToList());
        }

        public IActionResult Yeni()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Yeni(Hayvan hayvan)
        {
            if (ModelState.IsValid)
            {
                db.Hayvanlar.Add(hayvan);
                db.SaveChanges();
                return RedirectToAction("Index", new { Durum = "Eklendi" }); 
            }
            return View();
        }


        public IActionResult Sil(int id)
        {
            var hayvan = db.Hayvanlar.Find(id);
            if (hayvan == null)
                return NotFound();

            return View(hayvan);
        }

        [ActionName("Sil")]
        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult SilOnay(int id)
        {
            var hayvan = db.Hayvanlar.Find(id);
            if (hayvan == null)
                return NotFound();


            db.Hayvanlar.Remove(hayvan);
            db.SaveChanges();
            return RedirectToAction("Index", new { Durum = "Silindi" }); 
        }


        public IActionResult Duzenle(int id)
        {
            var hayvan = db.Hayvanlar.Find(id);
            if (hayvan == null)
                return NotFound();
            
            return View(hayvan);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public IActionResult Duzenle(Hayvan hayvan)
        {
            if (!db.Hayvanlar.Any(h => h.Id == hayvan.Id))
            {
                return NotFound();
            }

            if (ModelState.IsValid) //ad boş girilmiş olabilir, 50 karakterden fazla girilmiş olabilir geçerliliğini kontrol et
            {
                db.Hayvanlar.Update(hayvan);
                db.SaveChanges();
                return RedirectToAction("Index", new { Durum = "Duzenlendi" });   
            }

            return View();
        }
    }
}

EfCrud/Controllers/HomeController.cs
using EfCrud.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EfCrud.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EfCrud/Views/Hayvanlar/Duzenle.cshtml
@model Hayvan

@{ 
    ViewBag.Title = "Hayvan Düzenle";
}

<h1>Düzenle</h1>

<form asp-action="Duzenle" method="post">
    <input type="hidden" asp-for="Id"   />
    <div class="mb-3">
        <label asp-for="Ad" class="form-label">Ad</label>
        <input asp-for="Ad" type="text" class="form-control"  />
        <span asp-validation-for="Ad" class="text-danger"></span>
    </div>
    <button class="btn btn-primary" type="submit">Kaydet</button>  @*default submit*@
    <a asp-action="Index" class="btn btn-secondary">İptal</a>
</form>

EfCrud/Views/Hayvanlar/Index.cshtml
@model List<Hayvan>


@{
    ViewBag.Title = "Hayvanlar Listesi";
    string? durum = Context.Request.Query["Durum"];
    string? yuklem = durum == "Eklendi" ? "eklenmiştir" : durum == "Duzenlendi" ? "düzenlenmiştir" : durum == "Silindi" ? "silinmiştir" : null;
}

<h1>Hayvanlar Listesi</h1>


@if (yuklem != null)
{
    <div class="alert alert-success">
        Seçtiğiniz hayvan başarıyla @yuklem.

    </div>
}

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>Ad</th>
            <th></th>
        </tr>
    </thead>
      <tbody>
            @foreach (var hayvan in Model)
            {
                <tr>
                    <td>@hayvan.Id</td>
                    <td>@hayvan.Ad</td>
                    <td>
                        <a asp-controller="Hayvanlar" asp-action="Sil" asp-route-id="@hayvan.Id" class="btn btn-danger">Sil</a>
                        <a asp-controller="Hayvanlar" asp-action="Duzenle" asp-route-id="@hayvan.Id" class="btn btn-primary">Düzenle</a>
                    </td>
                </tr>
            }
      </tbody>
</table>

<a asp-action="Yeni" class="btn btn-success">Yeni Hayvan Ekle</a>

EfCrud/Views/Hayvanlar/Sil.cshtml
@model Hayvan

@{
    ViewBag.Title = "Silme Onay";
}

<h1>Silme Onay</h1>


<form asp-action="Sil" method="post">
    <div class="mb-3">

        <p>&quot;@Model.Ad&quot; isimli hayvan silinecektir. Onaylıyor musunuz?</p>
        <input type="hidden" asp-for="Id"/>
        <button class="btn btn-success">Evet</button>
        <a asp-action="Index" class="btn btn-secondary">Iptal</a>
    </div>

</form>

EfCrud/Views/Hayvanlar/Yeni.cshtml
@model Hayvan

@{
    ViewBag.Title = "Yeni Hayvan Ekle";
}

<h1>Yeni Hayvan Ekle</h1>

<form asp-action="Yeni" method="post">
    <div class="mb-3">
        <label asp-for="Ad" class="form-label">Ad</label>
        <input asp-for="Ad" type="text" class="form-control"/>
        <span asp-validation-for="Ad" class="text-danger"></span>
    </div>

    <button class="btn btn-primary" type="submit">Ekle</button>
    @*  <button class="btn btn-primary" type="button">Ekle</button> RESET için kullanılır*@
</form>

EfCrud/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

EfCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfCrud</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EfCrud.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EfCrud</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hayvanlar" asp-action="Index">Hayvanlar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - EfCrud - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>